export default function()
{
    return {
        "fire": {
            "color":"#ffffff",
            "backgroundColor":"#d6731f"
        },
        "all":
        {
            "color":"#ffffff", 
            "backgroundColor":"#000000"
        },
        "normal":
        {
            "color":"#000000",
            "backgroundColor":"#ffffff"
        },
        "fighting":
        {
            "color":"#ffffff",
            "backgroundColor":"#a00f41"
        },
        "flying":
        {
            "color":"#ffffff",
            "backgroundColor":"#7dc1e0"
        },
        "poison":
        {
            "color":"#ffffff",
            "backgroundColor":"#5d085a"
        },
        "ground":
        {
            "color":"#ffffff",
            "backgroundColor":"#a5a557"
        },
        "rock":
        {
            "color":"#ffffff",
            "backgroundColor":"#8d661e"
        },
        "bug":
        {
            "color":"#ffffff",
            "backgroundColor":"#5c763e"
        },
        "ghost":
        {
            "color":"#ffffff",
            "backgroundColor":"#3a0041"
        },
        "steel":
        {
            "color":"#ffffff",
            "backgroundColor":"#575757"
        },
        "water":
        {
            "color":"#ffffff",
            "backgroundColor":"#226ed6"
        },
        "grass":
        {
            "color":"#ffffff",
            "backgroundColor":"#2de04f"
        },
        "electric":
        {
            "color":"#ffffff",
            "backgroundColor":"#e2e23e"
        },
        "psychic":
        {
            "color":"#ffffff",
            "backgroundColor":"#d840b5"
        },
        "ice":
        {
            "color":"#ffffff",
            "backgroundColor":"#51eded"
        },
        "dragon":
        {
            "color":"#ffffff",
            "backgroundColor":"#122f8e"
        },
        "dark":
        {
            "color":"#ffffff",
            "backgroundColor":"#502e2e"
        },
        "fairy":
        {
            "color":"#ffffff",
            "backgroundColor":"#ebb3e3"
        }
    };
}